import {getEnv} from './../../helpers/config/get-env'
// prettier-ignore
const ALL_CONSTANTS = {
//Base Config
  BASE_LAYOUT_CONFIG_KEY: getEnv('BASE_LAYOUT_CONFIG_KEY'),
  API_URL               : getEnv('API_URL'),
  API_URL_2             : getEnv('API_URL_2'),
  API_URL_DSE           : getEnv('API_URL_DSE'),
  VERSION               : getEnv('VERSION'),
  THEME_NAME            : getEnv('THEME_NAME'),
  THEME_DEMO            : getEnv('THEME_DEMO'),
  SASS_PATH             : getEnv('SASS_PATH'),
  SASS_VARIABLES_PATH   : getEnv('SASS_VARIABLES_PATH'),
// Helpers
  BOOTSTRAP_DOCS_LINK: getEnv('BOOTSTRAP_DOCS_LINK'),
  PURCHASE_URL       : getEnv('PURCHASE_URL'),
  PREVIEW_URL        : getEnv('PREVIEW_URL'),
  PREVIEW_REACT_URL  : getEnv('PREVIEW_REACT_URL'),
  PREVIEW_DOCS_URL   : getEnv('PREVIEW_DOCS_URL'),
  THEME_API_URL      : getEnv('THEME_API_URL'),
// Auth
  AUTH_GET_USER_BY_ACCESS_TOKEN_PATH: getEnv('AUTH_GET_USER_BY_ACCESS_TOKEN_PATH'),
  AUTH_OTP_VALIDATE_PATH            : getEnv('AUTH_OTP_VALIDATE_PATH'),
  AUTH_LOGIN_PATH                   : getEnv('AUTH_LOGIN_PATH'),
  AUTH_REGISTER_PATH                : getEnv('AUTH_REGISTER_PATH'),
  AUTH_REQUEST_PASSWORD_PATH        : getEnv('AUTH_REQUEST_PASSWORD_PATH'),
  AUTH_SEND_VERIFY_CODE_PATH        : getEnv('AUTH_SEND_VERIFY_CODE_PATH'),
  AUTH_FORGOT_PASSWORD              : getEnv('AUTH_FORGOT_PASSWORD'),
  AUTH_OTP                          : getEnv('AUTH_OTP'),
// BO Account
  BO_GET_OPTION             : getEnv('BO_GET_OPTION'),
  BO_GET_TYPES              : getEnv('BO_GET_TYPES'),
  BO_GET_RESIDENCIES        : getEnv('BO_GET_RESIDENCIES'),
  BO_GET_DPS                : getEnv('BO_GET_DPS'),
  BO_GET_All_INFO           : getEnv('BO_GET_All_INFO'),
  BO_AC_CREATE              : getEnv('BO_AC_CREATE'),
  BO_LIST                   : getEnv('BO_LIST'),
  BO_INFO                   : getEnv('BO_INFO'),
  BO_COUNTRY_LIST           : getEnv('BO_COUNTRY_LIST'),
  BO_STATEMENTS_LIST        : getEnv('BO_STATEMENTS_LIST'),
  BO_CREATE_ADDRESS         : getEnv('BO_CREATE_ADDRESS'),
  BO_CREATE_NOMINEE_DETAILS : getEnv('BO_CREATE_NOMINEE_DETAILS'),
  BO_CREATE_BANK            : getEnv('BO_CREATE_BANK'),
  BO_AC_REFERENCE           : getEnv('BO_AC_REFERENCE'),
  BO_AC_UPDATE              : getEnv('BO_AC_UPDATE'),
  BO_FINISH                 : getEnv('BO_FINISH'),
  BO_BANK_INFO_UPDATE       : getEnv('BO_BANK_INFO_UPDATE'),
  BO_BANK_INFO_GET          : getEnv('BO_BANK_INFO_GET'),
  BO_BANK_INFO_CREATE       : getEnv('BO_BANK_INFO_CREATE'),
  BO_UPDATE_BANK_INFO_IMAGES: getEnv('BO_UPDATE_BANK_INFO_IMAGES'),
  BO_GET_NOMINEE_INFO       : getEnv('BO_GET_NOMINEE_INFO'),
  BO_UPDATE_NOMINEE_INFO    : getEnv('BO_UPDATE_NOMINEE_INFO'),
  BO_DELETE_NOMINEE_INFO    : getEnv('BO_DELETE_NOMINEE_INFO'),
  BO_CREATE_OTHER_INFO      : getEnv('BO_CREATE_OTHER_INFO'),
  BO_GET_OTHER_INFO         : getEnv('BO_GET_OTHER_INFO'),
  BO_UPDATE_OTHER_INFO      : getEnv('BO_UPDATE_OTHER_INFO'),
  BO_CREATE_ADDRESS_INFO    : getEnv('BO_CREATE_ADDRESS_INFO'),
  BO_GET_ADDRESS_INFO       : getEnv('BO_GET_ADDRESS_INFO'),
  BO_UPDATE_ADDRESS_INFO    : getEnv('BO_UPDATE_ADDRESS_INFO'),
// Trades
  TRADE_LIST                 : getEnv('TRADE_LIST'),
  TRADE_SELL                  : getEnv('TRADE_SELL'),
  TRADE_BUY                  : getEnv('TRADE_BUY'),
  TRADE_BASIC_INFO_DETAILS   : getEnv('TRADE_BASIC_INFO_DETAILS'),
  TRADE_CREATE_HOLDER_DETAILS: getEnv('TRADE_CREATE_HOLDER_DETAILS'),
  TRADE_UPDATE_HOLDER_DETAILS: getEnv('TRADE_UPDATE_HOLDER_DETAILS'),
  TRADE_BUY_BIT_TRADE        : getEnv('TRADE_BUY_BIT_TRADE'),
  TRADE_ASK_SELL             : getEnv('TRADE_ASK_SELL'),
  TRADE_BUY_SELL_BIT         : getEnv('TRADE_BUY_SELL_BIT'),
  TRADE_ALL_ORDERS_BUY       : getEnv('TRADE_ALL_ORDERS_BUY'),
  TRADE_ALL_ORDERS_SELL      : getEnv('TRADE_ALL_ORDERS_SELL'),
  TRADE_ALL_ORDERS           : getEnv('TRADE_ALL_ORDERS'),
  TRADE_COMPANIES            : getEnv('TRADE_COMPANIES'),
  TRADE_ALL_BUY_SELL_USER    : getEnv('TRADE_ALL_BUY_SELL_USER'),
  TRADE_COMPANY              : getEnv('TRADE_COMPANY'),
  // User
  USER_INFO             : getEnv('USER_INFO'),
  USER_INFO_UPDATE      : getEnv('USER_INFO_UPDATE'),
  USER_BO_INFO          : getEnv('USER_BO_INFO'),
  USER_BO_INFO_2          : getEnv('USER_BO_INFO_2'),
  USER_ORDER_LIST       : getEnv('USER_ORDER_LIST'),
  USER_PORTFOLIO        : getEnv('USER_PORTFOLIO'),
  USER_TRANSACTIONS     : getEnv('USER_TRANSACTIONS'),
  USER_AVAILABLE_BALANCE: getEnv('USER_AVAILABLE_BALANCE'),
  USER_CREATE_ADDRESS   : getEnv('USER_CREATE_ADDRESS'),
  USER_PROFIT           : getEnv('USER_PROFIT'),
  USER_PROFILE_UPDATE   : getEnv('USER_PROFILE_UPDATE'),
  USER_THEME            : getEnv('USER_THEME'),
  USER_THEME_CREATE     : getEnv('USER_THEME_CREATE'),
  USER_THEME_GET        : getEnv('USER_THEME_GET'),
  USER_THEME_UPDATE     : getEnv('USER_THEME_UPDATE'),
  USER_THEME_DELETE     : getEnv('USER_THEME_DELETE'),
  
  // Table
  USER_TABLE_LIST     : getEnv("USER_TABLE_LIST"),
  USER_TABLE_LAYOUT     : getEnv('USER_TABLE_LAYOUT'),
  USER_TABLE_COLUMNS  : getEnv("USER_TABLE_COLUMNS"),
  TABLE_COLUMNS_UPDATE  : getEnv("USER_TABLE_COLUMNS_UPDATE"),

  //global 
  SYSTEM_ALL_TABLE_LIST  : getEnv("SYSTEM_ALL_TABLE_LIST"),

  TRADE_LIST_SOCKET: getEnv('TRADE_LIST_SOCKET'),


  API_TEST: getEnv('API_TEST'),
}

export default ALL_CONSTANTS
