import {fullLayoutInterface, InitLayoutPartInterface} from '#common/types/layout'
const availableHandles = ['s', 'w', 'e', 'n', 'sw', 'nw', 'se', 'ne']

const smallDevice: InitLayoutPartInterface[] = [
  {
    x: 0,
    y: 0,
    w: 6,
    h: 47,
    i: 'trading_GROUP',
    component_type: 'marketData',
    static: true,
    isBounded: undefined,
    isDraggable: undefined,
    isResizable: undefined,
    maxH: undefined,
    maxW: undefined,
    minH: undefined,
    minW: undefined,
    moved: false,
    resizeHandles: availableHandles,
  },
  {
    x: 0,
    y: 0,
    w: 6,
    h: 47,
    i: 'trading_copy_GROUP',
    component_type: 'marketData',
    static: true,
    isBounded: undefined,
    isDraggable: undefined,
    isResizable: undefined,
    maxH: undefined,
    maxW: undefined,
    minH: undefined,
    minW: undefined,
    moved: false,
    resizeHandles: availableHandles,
  },
  {
    x: 6,
    y: 0,
    w: 6,
    h: 33,
    i: 'buy_sell',
    component_type: 'buySell',
    static: true,
    isBounded: undefined,
    isDraggable: undefined,
    isResizable: undefined,
    maxH: undefined,
    maxW: undefined,
    minH: undefined,
    minW: undefined,
    moved: false,
    resizeHandles: availableHandles,
  },
  {
    x: 7,
    y: 33,
    w: 6,
    h: 38,
    i: 'blotter_INDIVIDUAL',
    component_type: 'blotter',
    static: true,
    isBounded: undefined,
    isDraggable: undefined,
    isResizable: undefined,
    maxH: undefined,
    maxW: undefined,
    minH: undefined,
    minW: undefined,
    moved: false,
    resizeHandles: availableHandles,
  },
]

const initLayout: fullLayoutInterface = {
  lg: [
    {
      x: 0,
      y: 0,
      w: 6,
      h: 47,
      i: 'trading_GROUP',
      component_type: 'marketData',
      static: true,
      isBounded: undefined,
      isDraggable: undefined,
      isResizable: undefined,
      maxH: undefined,
      maxW: undefined,
      minH: undefined,
      minW: undefined,
      moved: false,
      resizeHandles: availableHandles,
    },
    {
      x: 6,
      y: 0,
      w: 6,
      h: 33,
      i: 'buySell_MARKET',
      component_type: 'buySell',
      static: true,
      isBounded: undefined,
      isDraggable: undefined,
      isResizable: undefined,
      maxH: undefined,
      maxW: undefined,
      minH: undefined,
      minW: undefined,
      moved: false,
      resizeHandles: availableHandles,
    },
    {
      x: 6,
      y: 33,
      w: 6,
      h: 38,
      i: 'blotter_INDIVIDUAL',
      component_type: 'blotter',
      static: true,
      isBounded: undefined,
      isDraggable: undefined,
      isResizable: undefined,
      maxH: undefined,
      maxW: undefined,
      minH: undefined,
      minW: undefined,
      moved: false,
      resizeHandles: availableHandles,
    },
    {
      x: 0,
      y: 71,
      w: 6,
      h: 29,
      i: 'moversGainers_INDIVIDUAL',
      component_type: 'moversGainers',
      static: true,
      isBounded: undefined,
      isDraggable: undefined,
      isResizable: undefined,
      maxH: undefined,
      maxW: undefined,
      minH: undefined,
      minW: undefined,
      moved: false,
      resizeHandles: availableHandles,
    },
    {
      x: 6,
      y: 71,
      w: 6,
      h: 29,
      i: 'execution_INDIVIDUAL',
      component_type: 'execution',
      static: true,
      isBounded: undefined,
      isDraggable: undefined,
      isResizable: undefined,
      maxH: undefined,
      maxW: undefined,
      minH: undefined,
      minW: undefined,
      moved: false,
      resizeHandles: availableHandles,
    },
    {
      x: 0,
      y: 47,
      w: 6,
      h: 24,
      i: 'orderSummery_INDIVIDUAL',
      component_type: 'orderSummery',
      static: true,
      isBounded: undefined,
      isDraggable: undefined,
      isResizable: undefined,
      maxH: undefined,
      maxW: undefined,
      minH: undefined,
      minW: undefined,
      moved: false,
      resizeHandles: availableHandles,
    },
    {
      x: 0,
      y: 100,
      w: 4,
      h: 29,
      i: 'position_INDIVIDUAL',
      component_type: 'position',
      static: true,
      isBounded: undefined,
      isDraggable: undefined,
      isResizable: undefined,
      maxH: undefined,
      maxW: undefined,
      minH: undefined,
      minW: undefined,
      moved: false,
      resizeHandles: availableHandles,
    },
    {
      x: 4,
      y: 100,
      w: 4,
      h: 29,
      i: 'news_INDIVIDUAL',
      component_type: 'news',
      static: true,
      isBounded: undefined,
      isDraggable: undefined,
      isResizable: undefined,
      maxH: undefined,
      maxW: undefined,
      minH: undefined,
      minW: undefined,
      moved: false,
      resizeHandles: availableHandles,
    },
    {
      x: 8,
      y: 100,
      w: 4,
      h: 29,
      i: 'report_INDIVIDUAL',
      component_type: 'report',
      static: true,
      isBounded: undefined,
      isDraggable: undefined,
      isResizable: undefined,
      maxH: undefined,
      maxW: undefined,
      minH: undefined,
      minW: undefined,
      moved: false,
      resizeHandles: availableHandles,
    },
    // {
    //   x: 0,
    //   y: 130,
    //   w: 8,
    //   h: 29,
    //   i: 'trading2_GROUP',
    //   component_type: 'marketData',
    //   static: true,
    //   isBounded: undefined,
    //   isDraggable: undefined,
    //   isResizable: undefined,
    //   maxH: undefined,
    //   maxW: undefined,
    //   minH: undefined,
    //   minW: undefined,
    //   moved: false,
    //   resizeHandles: availableHandles,
    // },
  ],
  md: [],
  sm: smallDevice,
  xs: smallDevice,
  xxs: smallDevice,
}

export default initLayout
