import {ColDef, ValueParserParams} from 'ag-grid-community'

function numberValueParser(params: ValueParserParams) {
  return Number(params.newValue)
}

const ORDER_SUMMERY_TABLE_INIT_VALUE: ColDef[] = [
  {
    field: 'order',
    headerName: 'Order',
    hide: false,
    width: 140,
    type: 'textColumn',
  },
  {
    field: 'tot',
    headerName: 'Total Order Qty',
    hide: false,
    width: 140,
    type: 'textColumn',
  },
  {
    field: 'tot_val',
    headerName: 'Tot Order Value',
    hide: false,
    width: 110,
    type: 'numColumn',
    valueParser: numberValueParser,
    cellRenderer: 'agAnimateSlideCellRenderer',
  },
  {
    field: 'trq',
    headerName: 'Total Rem Qty',
    hide: false,
    width: 130,
    type: 'numColumn',
    valueParser: numberValueParser,
    cellRenderer: 'agAnimateShowChangeCellRenderer',
  },
  {
    field: 'beq',
    headerName: 'Buy Exec Qty',
    hide: false,
    width: 140,
    type: 'numColumn',
    valueParser: numberValueParser,
    cellRenderer: 'agAnimateShowChangeCellRenderer',
  },
  {
    field: 'bev',
    headerName: 'Buy Exec Val',
    hide: false,
    width: 140,
    type: 'numColumn',
    valueParser: numberValueParser,
    cellRenderer: 'agAnimateShowChangeCellRenderer',
  },
  {
    field: 'bap',
    headerName: 'Buy Avg Price',
    hide: false,
    width: 140,
    type: 'numColumn',
    valueParser: numberValueParser,
    cellRenderer: 'agAnimateShowChangeCellRenderer',
  },
  {
    field: 'seq',
    headerName: 'Sell Exec Qty',
    hide: false,
    width: 140,
    type: 'numColumn',
    valueParser: numberValueParser,
    cellRenderer: 'agAnimateShowChangeCellRenderer',
  },
  {
    field: 'sev',
    headerName: 'Sell Exec Value',
    hide: false,
    width: 140,
    type: 'numColumn',
    valueParser: numberValueParser,
    cellRenderer: 'agAnimateShowChangeCellRenderer',
  },
  {
    field: 'svp',
    headerName: 'Sell Avg Price',
    hide: false,
    width: 140,
    type: 'numColumn',
    valueParser: numberValueParser,
    cellRenderer: 'agAnimateShowChangeCellRenderer',
  },
  {
    field: 'teq',
    headerName: 'Tot Exec Qty',
    hide: false,
    width: 140,
    type: 'numColumn',
    valueParser: numberValueParser,
    cellRenderer: 'agAnimateShowChangeCellRenderer',
  },
  {
    field: 'tev',
    headerName: 'Tot Exec Value',
    hide: false,
    width: 140,
    type: 'numColumn',
    valueParser: numberValueParser,
    cellRenderer: 'agAnimateShowChangeCellRenderer',
  },
  {
    field: 'neq',
    headerName: 'Net Exec Qty',
    hide: false,
    width: 140,
    type: 'numColumn',
    valueParser: numberValueParser,
    cellRenderer: 'agAnimateShowChangeCellRenderer',
  },
  {
    field: 'nev',
    headerName: 'Net Exec Value',
    hide: false,
    width: 140,
    type: 'numColumn',
    valueParser: numberValueParser,
    cellRenderer: 'agAnimateShowChangeCellRenderer',
  },
]

export default ORDER_SUMMERY_TABLE_INIT_VALUE
